### ISSUE TITLE
pcre no longer available

### ISSUE THREAD

**Issue by hainesbg** [talos-systems/tools#154]
The source package for pcre is no longer available. From the pcre.org website:

> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

Unfortunately versions older than 10.0 are not on the github site referenced. As such, I cannot build the tools. :(

**Comment by AlekSi** [comment]
It still can be downloaded from https://sourceforge.net/projects/pcre/files/pcre/.

Would you send a PR?

**Comment by hainesbg** [comment]
Sure thing. I've also taken the opportunity to upgrade it to the latest (and last, according to the ChangeLog) point release: https://github.com/talos-systems/tools/pull/155
